### ISSUE TITLE
error message:sigprocmask: Invalid argument. 

### ISSUE THREAD

**Issue by stayliv3** [mzpqnxow/gdb-static-cross#1]
use gdbserver-7.12-mips-mip32rel2-v1-sysv and always got the message:

`sigprocmask: Invalid argument. `

the google result seems it is a gdb bug.
https://bugs.lede-project.org/index.php?do=details&task_id=637

```
I’ve tried to debug some code using GDB server on target device (Ubiquity AP AC PRO MIPS32r2) and I’ve found that it doesn’t work.

I’m using std command to run GDB server: “gdbserver :9000 <application_to_debug>” and I always get “sigprocmask: Invalid argument.”.

I’ve made short investigation to find root cause of this problem and it seems that problem is located in GDB in file: “gdb/common/signals-state-save-restore.c” in line “res = sigprocmask (0, NULL, &original_signal_mask);”. According to linux kernel documentation function “sigprocmask” always return “-EINVAL” when it is called with invalid “how” argument (in this case how == 0). I’ve fixed GDB by removing “if” statement that checks if “res < 0”. After this operation GDB server works properly.


```

**Comment by mzpqnxow** [comment]
great, thanks for identifying and tracking this down. Would you mind doing a diff -Naur gdb-7.12 gdb-7.12-fixed > gdbserver-7.12-mips32rel2.patch and create a pull request by adding the patch file to the root of the repo or in a patches/ directory with a small note in the readme?

**Comment by mzpqnxow** [comment]
@stayliv3 I added a patch and rebuilt the sysv version of the mips binary (accidentally without soft float) and will be rebuilding with proper soft float and updating in a few moments... thanks again for bringing this to my attention :>

As I get a chance I will rebuild for mipsel-sysv/mipsel

**Comment by mzpqnxow** [comment]
I rebuilt and checked in all 4 of the mips32r2 binaries: MSB, LSB, MSB SYSV, LSB SYSV in case you (or anyone) wants to use them in the future

**Comment by stayliv3** [comment]
really appreciate your work。 sorry for my C programming skill。

**Comment by mzpqnxow** [comment]
No problem, it only took an hour, I hadn't tested that particular build so
I'm happy you found the bug and tracked it down, it would have been
annoying later when I used that version the first time :>
